### PR TITLE
Remove unnecessary prepend of test with current folder

### LINKED ISSUE #115: WebStorm IDE Instructions Not Working - Incorrect relative path prefix inserted in front of absolute paths causing Exit Code 1
[IDE Instructions](http://zinserjan.github.io/mocha-webpack/docs/guides/ide-integration.html) for WebStorm 2017 do not seem to work, or I am configuring something incorrectly.

I have both VS Code, and npm command line working fine in bash shell, but need WebStorm due to better (live) debugger integration that currently possible in VS Code.

When running a debug session in WebStorm, it appears mocha-webpack is prefixing a relative path (`./../../..`) in front of absolute paths when trying to import modules.

ERROR OUTPUT:
```
WEBPACK  Compiling...

WEBPACK  Failed to compile with 1 error(s)

Error in ./~/mocha-webpack/lib/entry.js

Module not found: './../../../Users/n8/dev/project_workspace/test/model-tests/Widgets.test.ts' in '/Users/n8/dev/project_workspace/node_modules/mocha-webpack/lib'


Process finished with exit code 1
```

### PR DESCRIPTION
**Pull request by pkuczynski**
Allow running individual tests from WebStorm environment. Works well also outside of WebStorm.

Fixes #115

### CODE REVIEW

**Comment by pkuczynski** [comment]
@zinserjan could you please review this change and release `1.0.0-beta.2`? It's kind of urgent for my team to be able to run the tests from within WebStorm environment :)

**Comment by zinserjan** [comment]
@pkuczynski looks like all tests with relative entries are failing, so this isn't a solution.
It would be better to check for absolute paths instead of skipping this step.

**Comment by pkuczynski** [comment]
I noticed that tests are failing. I will have a look on Monday, ok?

**Comment by zinserjan** [comment]
Sure, sounds good for me.

Btw I just found the PR that added this absolute path handling: #106.

I think bumping the `glob` version in `globby` to at least 7.1 and reverting #106 could fix this.

**Comment by pkuczynski** [comment]
@zinserjan how would you like to bump `glob` in `globby` if that's an external package?

**Comment by zinserjan** [comment]
@pkuczynski sending a PR there is the only reliable way to make sure that we are using a version that works with absolute paths.

But before you can try this out on your project.

**Comment by pkuczynski** [comment]
I reverted the changes as you suggested, but 4 tests still fail:
* `cli --watch should run only the changed test again when it changes`
* `cli --watch should recognize new test entries that match the pattern`
* `cli --watch should recognize multiple new test entries that match the pattern`
* `cli --watch should recognize deleted test entries that match the pattern`

Even if I updated local installation of globby to use glob 7.1.

**Comment by zinserjan** [comment]
CI tests aren't failing, just the linting fails. For local development rebase your branch. I made several changes to make the tests working again :)

**Comment by pkuczynski** [comment]
Indeed, I was removing a comma instead of adding it. Different linting style then the one I am used to :)

**Comment by zinserjan** [comment]
Looks like the rebase rewrote the whole history. Can you fix this so that only your commits applied to the latest master?

**Comment by pkuczynski** [comment]
I can confirm, that after re-base all the tests pass. It it did not require changing glob version in globby! Are we good to merge?

**Comment by pkuczynski** [comment]
PR rebased against latest `upstream/master`

**Comment by zinserjan** [comment]
> It it did not require changing glob version in globby! Are we good to merge?

No, bumping the version in globby is the only reliable way to make sure that the absolute path option is available. We cannot rely on npms module hoisting as it fails with npm@2 and it could also fail if another package needs glob < 7.1 and cause of the matching of glob > 7.0 in globby we will get 7.0 for glob :( That was the reason why I did #106, but I wasn't aware of the drawbacks... It was just the simplest solution...

History is still messed up, but githubs squashing should fix this :D

**Comment by pkuczynski** [comment]
PR requested https://github.com/sindresorhus/globby/pull/45

**Comment by pkuczynski** [comment]
@zinserjan could you please comment in https://github.com/sindresorhus/globby/pull/45?

**Comment by zinserjan** [comment]
I think we should start to work an a different approach to speed things up and just ensure the absolute paths manually.

Can you work on this on a different PR? So we can keep this open and merge it someday.

I think something like this could work:
```js
import path from "path";
import normalizePath from "normalize-path"
function ensureAbsolutePath(path, basePath) {
  return path.posix.isAbsolute(path) || path.win32.isAbsolute(path)  ? path : path.join(basePath, path);
}
```

**Comment by pkuczynski** [comment]
Not sure if its worth the effort if undoing #106 make it work anyway.

**Comment by zinserjan** [comment]
I added a temporary workaround to fix this issue (#160). 

We can continue the work on this PR when a new version of globby is available.

**Comment by astorije** [comment]
@pkuczynski, would you like to rebase on `master` and fix conflicts? (also squash commits)

**Comment by pkuczynski** [comment]
Done

**Comment by pkuczynski** [comment]
You can squash in GH interface, right?

**Comment by zinserjan** [comment]
Yep.

The `ensureAbsolutePath` workaround introcuded with #160 is no longer necessary with this change. Can you remove that also?

**Comment by pkuczynski** [comment]
Sure. Done. Should I also remove it from https://github.com/zinserjan/mocha-webpack/blob/13214ae3bd6d845b05fcf2ed76dca8ebc066f103/src/webpack/compiler/registerInMemoryCompiler.js#L21 ?

**Comment by zinserjan** [comment]
Good question. If I remember correctly, webpack emits just relative file paths.

**Comment by zinserjan** [comment]
Yep. Thank you! :wink:

**Pull request merged**
