### PR TITLE
Update eslint-config-airbnb-base and eslint-plugin-import to their latest version

### PR DESCRIPTION
**Pull request by astorije**
Well that was fun 😅

@zinserjan, there are 3 failures left at this point, I have fixed everything else on a best-guess basis, would you mind letting me know what you want me to do with the last ones?
Also, some changes I made seem questionable, but I was really just trying to please the linter, not make personal calls :) If you see something you don't like, please feel free to tell me what you want instead.

Finally, I didn't look at any additions made by the version upgrade, simply bumped `package.json` and then tried to fix the failures. There are probably more you want to add/update.

(This is a bit painful to keep track of over time, I strongly suggest using something like Greenkeeper to make sure that new versions don't break tests/linter)

### CODE REVIEW

**Comment by zinserjan** [comment]
Awesome, thanks for this! This looks like a lot of work...

Personally, I prefer to use parenthesis for arrow functions always. I think it's inconsistent to use them for longer arrow functions with return statements, but don't use them for the compact variant. And when you don't have any function arguments, you have to use paranethesis :neutral_face:

If this rule can be fixed with eslint autofix, I would prefer to use parenthesis always. Otherwise just keep it as it is.

```
/home/travis/build/zinserjan/mocha-webpack/src/cli/parseArgv.js
  256:9  error  Use array destructuring  prefer-destructuring
```
=> Disable this error for this line. This code was just copied from mocha to parse reporter options and I would keep it as ugly as it is. :laughing:

```
/home/travis/build/zinserjan/mocha-webpack/src/util/registerRequireHook.js
  36:3  error  iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations  no-restricted-syntax
```

=> I would disable this rule globally. Iteraters are supported in our node version range.

```
/home/travis/build/zinserjan/mocha-webpack/src/webpack/util/createStatsFormatter.js
  66:11  error  Use object destructuring  prefer-destructuring
```
=> Use object destructuring and get rid of the type annotation for compilation. Type of compilation is already declared in Stats.

> This is a bit painful to keep track of over time, I strongly suggest using something like Greenkeeper to make sure that new versions don't break tests/linter

Yep that's true. Greenkeeper is a good idea to test if our tests are still running. The only annoying part is the huge PR spam...

**Comment by astorije** [comment]
> => I would disable this rule globally. Iteraters are supported in our node version range.

I can do that but [because of how this rule is defined](https://github.com/airbnb/javascript/blob/a100a3957ffb11c841dbd74a649cbb9b5a17a2aa/packages/eslint-config-airbnb-base/rules/style.js#L321-L341), I need to re-define `no-restricted-syntax` with all but `ForOfStatement`. Are you okay with me doing that, or do you want to do something else?

**Comment by zinserjan** [comment]
Disabling the rule completely and ignoring the other options of this rule is OK for me.

**Comment by astorije** [comment]
> If this rule can be fixed with eslint autofix, I would prefer to use parenthesis always. Otherwise just keep it as it is.

Done! I personally prefer the "when needed" way (though that didn't influence this PR, I just went with what airbnb config was recommending) but I understand where you come from. And more importantly, it's your project :D

> => Disable this error for this line.

Done.

> => Use object destructuring and get rid of the type annotation for compilation.

Done.

> Disabling the rule completely and ignoring the other options of this rule is OK for me.

Done.

> Greenkeeper is a good idea to test if our tests are still running. The only annoying part is the huge PR spam...

I believe there is a way to configure Greenkeeper so it only opens PRs if builds break, otherwise it just deletes the branch when CI comes back successful. Not sure though.

**Comment by astorije** [comment]
👍

**Comment by zinserjan** [comment]
Thank you!
Added some commits to "fix" the flow error and to ensure that line breaks are always lf for Windows users that use autocrlf. Noted this only cause I checked it out on my Windows PC  :laughing:

**Comment by astorije** [comment]
That's awesome @zinserjan! Are you planning on making a release?

**Comment by zinserjan** [comment]
Yep, just finished the last piece #222 :D

**Pull request merged**
