### PR TITLE
tweak peerDependencies for webpack 2

### PR DESCRIPTION
**Pull request by zinserjan**
Tweaks the semver constraints to allow the latest versions of webpack 2.

### CODE REVIEW

**Comment by TimPetricola** [comment]
@zinserjan do you think it would be possible to release a `0.7.1` version with this change?

**Comment by zinserjan** [comment]
@TimPetricola 
I would like to avoid that :grin:

Most of the programming tasks for a pre-release for 1.0.0 are done so I would like to spend my time on this instead.

**Comment by TimPetricola** [comment]
@zinserjan I totally understand :)

**Comment by zinserjan** [comment]
@TimPetricola 

Just published the first beta for 1.0.0. You can install it via `npm install mocha-webpack@next`.

**Comment by TimPetricola** [comment]
@zinserjan Thanks for letting me know, I'll give it a try :)

**Pull request merged**
